---
- name: Set up Traefik on Raspberry Pi
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Create Traefik configuration directory
      file:
        path: /opt/traefik
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create acme.json file for Let's Encrypt
      file:
        path: /opt/traefik/acme.json
        state: touch
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy Traefik static configuration file
      template:
        src: ../templates/traefik_config.yml.j2
        dest: /opt/traefik/traefik.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy Docker Compose file for Traefik
      template:
        src: ../templates/traefik_docker_compose.yml.j2
        dest: /opt/traefik/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Start Traefik service using Docker Compose
      shell: docker compose up -d
      args:
        chdir: /opt/traefik
      register: traefik_up
      changed_when: "'Started container' in traefik_up.stdout or 'Creating' in traefik_up.stdout"

    - name: Ensure Traefik service is up
      shell: docker ps --filter "name=traefik" --format "{{ '{{' }}.Names{{ '}}' }}"
      register: traefik_ps
      changed_when: false
      failed_when: traefik_ps.stdout.find('traefik') == -1
