- name: Deploy Home Assistant with Traefik Integration
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Ensure Docker network for Traefik exists
      docker_network:
        name: traefik_net
        state: present

    - name: Create directory for Home Assistant configuration
      file:
        path: /home/{{ ansible_user }}/homeassistant
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Pull Home Assistant Docker image
      docker_image:
        name: ghcr.io/home-assistant/home-assistant
        tag: stable
        source: pull

    - name: Find Zigbee USB stick
      shell: "ls /dev/serial/by-id/ | grep -i 'usb-Itead_Sonoff_Zigbee'"
      register: zigbee_device_output
      changed_when: false

    - name: Fail if Zigbee USB stick is not found
      fail:
        msg: "Zigbee USB stick not found. Ensure it is plugged in and the correct pattern matches."
      when: zigbee_device_output.stdout == ""

    - name: Get full Zigbee device path
      set_fact:
        zigbee_device: "/dev/serial/by-id/{{ zigbee_device_output.stdout }}"

    - name: Debug Zigbee device path
      debug:
        msg: "Detected Zigbee device path: {{ zigbee_device }}"

    - name: Ensure the user is in the dialout group
      user:
        name: "{{ ansible_user }}"
        groups: dialout
        append: true

    - name: Ensure correct permissions on Zigbee device
      file:
        path: "{{ zigbee_device }}"
        owner: root
        group: dialout
        mode: '0660'

    - name: Copy Home Assistant Docker Compose file
      template:
        src: ../templates/home_assistent_docker_compose.yml.j2
        dest: /home/{{ ansible_user }}/homeassistant/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Stop and remove existing Home Assistant container if it exists
      shell: |
        if docker ps -a --filter "name=homeassistant" --format "{{ '{{.Names}}' }}" | grep -q homeassistant; then
          docker stop homeassistant && docker rm homeassistant
        fi
      args:
        chdir: /home/{{ ansible_user }}/homeassistant
      register: container_cleanup
      ignore_errors: true

    - name: Run Home Assistant with Docker Compose
      shell: docker compose up -d
      args:
        chdir: /home/{{ ansible_user }}/homeassistant
