# playbooks/deploy_traefik.yml

- name: Deploy Traefik as Reverse Proxy with DNS-01 Challenge
  hosts: raspberrypi
  become: yes
  vars:
    traefik_config_dir: /home/{{ ansible_user }}/traefik
  tasks:
    - name: Create Traefik configuration directory
      file:
        path: "{{ traefik_config_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create acme.json file for Let's Encrypt
      file:
        path: "{{ traefik_config_dir }}/acme.json"
        state: touch
        mode: '600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create Traefik configuration file
      template:
        src: ../templates/traefik.yml.j2
        dest: "{{ traefik_config_dir }}/traefik.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Run Traefik container
      docker_container:
        name: traefik
        image: traefik:v2.9
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "{{ traefik_config_dir }}/traefik.yml:/traefik.yml:ro"
          - "{{ traefik_config_dir }}/acme.json:/acme.json"
        env:
          CF_API_TOKEN: "{{ cloudflare_api_token }}"
        labels:
          traefik.enable: "true"
