# Untestet
- name: Deploy AdGuard Home in Docker
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Create directory for AdGuard Home configuration
      file:
        path: /home/{{ ansible_user }}/adguard
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Pull AdGuard Home Docker image
      docker_image:
        name: adguard/adguardhome
        source: pull

    - name: Run AdGuard Home container
      docker_container:
        name: adguardhome
        image: adguard/adguardhome
        restart_policy: always
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "67:67/udp"
          # - "68:68/udp" conflicts with the network manager
          - "80:80/tcp"
          - "443:443/tcp"
          - "3000:3000/tcp"
        volumes:
          - /home/{{ ansible_user }}/adguard/work:/opt/adguardhome/work
          - /home/{{ ansible_user }}/adguard/conf:/opt/adguardhome/conf
