# Untestet
- name: Deploy Home Assistant in Docker
  hosts: raspberrypi
  become: yes
  vars:
    domain: "ha.{{ domain }}"  # Replace with your subdomain
  tasks:
    - name: Create directory for Home Assistant configuration
      file:
        path: /home/{{ ansible_user }}/homeassistant
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Run Home Assistant container
      docker_container:
        name: homeassistant
        image: homeassistant/home-assistant:stable
        restart_policy: always
        network_mode: bridge  # Use bridge network for Traefik compatibility
        ports:
          - "8123"  # Expose internal port
        volumes:
          - /home/{{ ansible_user }}/homeassistant:/config
        environment:
          - TZ={{ timezone }} # Replace with your timezone
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.homeassistant.rule=Host(`{{ domain }}`)"
          - "traefik.http.routers.homeassistant.entrypoints=websecure"
          - "traefik.http.routers.homeassistant.tls.certresolver=letsencrypt"
          - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
